### ISSUE TITLE
Update to latest alloy

### ISSUE THREAD

**Issue by NicolasWent** [dexloom/loom#11]
[Alloy](https://github.com/alloy-rs/alloy) updated to version `0.3.1` and [alloy-core](https://github.com/alloy-rs/core) updated to version `0.8.0` which makes all new alloy projects incompatible with this crate.

Could you please update to latest alloy version?

**Comment by dexloom** [comment]
Done : 2518a349863e5adacf183d63819e8e21fd83d4be
