### ISSUE TITLE
[Feature] Specify signer in Flashbots

### ISSUE THREAD

**Issue by NicolasWent** [dexloom/loom#4]
Hello,

It would be great to be able to manually specify the signer in [Flashbots](https://github.com/dexloom/loom/blob/72f59ee10f870a0c146e55b122ceeba773e8ca1f/crates/flashbots/src/flashbots.rs#L109) this way we can use same reputation for all of our bundles instead of using a random signer each time.

Maybe create an Option<PrivateKeySigner> in Flashbots constructor this way we can specify the signer if we want or use a random one if we don't

**Comment by dexloom** [comment]
Fixed in 33ee53108b19cf14eb426c390e2777689e108bdf
